site_name: Just another software blog
site_url: https://tunayan.github.io
theme: gitbook
nav:
  - Home: index.md
  - Test1: test1.md
  - Test2: 
    - sect/test2.md
    - sect/test3.md

extra:
  nav:
    sort_order: reverse

plugins:
    - search
    - awesome-pages

repo_url: https://github.com/tunayan/tunayan.github.io