site_name: Just another software blog
site_url: https://tunayan.github.io
theme: gitbook
nav:
  - Home: index.md
  - test1: test1
  - test2: 
    - sect/test2
    - sect/test3

extra:
  nav:
    sort_order: reverse

plugins:
    - search
    - awesome-pages